#!/usr/bin/env node
// Renders the Homebrew formula for nexdrew/homebrew-tap from a GitHub release.
//
//   gh api repos/nexdrew/blitzy-cli/releases/latest | node scripts/homebrew-formula.mjs
//   gh api repos/nexdrew/blitzy-cli/releases/tags/v1.1.0 | node scripts/homebrew-formula.mjs
//
// Reads the release JSON on stdin, extracts the tag and the sha256 digests that
// GitHub records for each uploaded asset, and prints the formula to stdout. The
// release workflow pipes this into Formula/blitzy-cli.rb in the tap repo; the
// formula is fully generated — never edit it by hand.

import { readFileSync } from 'node:fs'

const release = JSON.parse(readFileSync(0, 'utf8'))

const tag = release.tag_name
if (!/^v\d+\.\d+\.\d+$/.test(tag || '')) {
  console.error(`Unexpected tag_name: ${tag}`)
  process.exit(1)
}
const version = tag.slice(1)

// Formula platforms -> release asset names (musl/windows aren't brew targets).
const ASSETS = {
  darwinArm: 'blitzy-darwin-arm64',
  darwinIntel: 'blitzy-darwin-x64',
  linuxArm: 'blitzy-linux-arm64',
  linuxIntel: 'blitzy-linux-x64'
}

function sha256 (assetName) {
  const asset = (release.assets || []).find((a) => a.name === assetName)
  const digest = asset && asset.digest
  if (!digest || !digest.startsWith('sha256:')) {
    console.error(`Release ${tag} is missing a sha256 digest for asset ${assetName}`)
    process.exit(1)
  }
  return digest.slice('sha256:'.length)
}

const url = (assetName) =>
  `https://github.com/nexdrew/blitzy-cli/releases/download/${tag}/${assetName}`

console.log(`# frozen_string_literal: true

# GENERATED by scripts/homebrew-formula.mjs in nexdrew/blitzy-cli — do not edit
# by hand; the blitzy-cli release workflow regenerates this on every release.
class BlitzyCli < Formula
  desc "Unofficial CLI for the Blitzy platform API"
  homepage "https://github.com/nexdrew/blitzy-cli"
  version "${version}"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "${url(ASSETS.darwinArm)}"
      sha256 "${sha256(ASSETS.darwinArm)}"
    end
    on_intel do
      url "${url(ASSETS.darwinIntel)}"
      sha256 "${sha256(ASSETS.darwinIntel)}"
    end
  end

  on_linux do
    on_arm do
      url "${url(ASSETS.linuxArm)}"
      sha256 "${sha256(ASSETS.linuxArm)}"
    end
    on_intel do
      url "${url(ASSETS.linuxIntel)}"
      sha256 "${sha256(ASSETS.linuxIntel)}"
    end
  end

  def install
    bin.install Dir["blitzy-*"].first => "blitzy"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/blitzy --version")
  end
end`)
